# Generated by Django 3.0.8 on 2020-08-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pews', '0003_auto_20200805_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='created_date'),
        ),
    ]
