# Generated by Django 3.1.2 on 2021-02-12 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pews', '0005_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст пiдзаголовка')),
                ('textcontent', models.TextField(null=True, verbose_name='Текст новини')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('slug', models.SlugField(max_length=250, null=True, unique_for_date='created_date')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата створення')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='дата публiкацii')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
